[biolink]
supplemental_prefixes = ["CHR", "CLYH"]

[edges_attribute_checks]
checks = [
    { range = { column = "_Coexpression", min = "80", max = "1000" } },
    { range = { column = "_Coexpression_transferred", min = "80", max = "1000" } },
    { range = { column = "_Experiments", min = "0", max = "1000" } },
    { range = { column = "_Experiments_transferred", min = "0", max = "1000" } },
    { range = { column = "_Database", min = "0", max = "1000" } },
    { range = { column = "_Database_transferred", min = "0", max = "1000" } },
    { range = { column = "_Textmining", min = "0", max = "1000" } },
    { range = { column = "_Textmining_transferred", min = "0", max = "1000" } }
]

[nodes_attribute_checks]
checks = [
    { range = { column = "_information_content", min = "20", max = "100" } },
    { enum = { column = "_locus_group", nullable = true, values = [ "protein-coding gene", "non-coding RNA", "pseudogene", "other" ] } },
]

